import sys

from twisted.internet import wxreactor

from wxPython import wx
from wxPython import xrc

someXrc = """<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by wxGlade 0.3.3 on Sat Aug 14 13:14:29 2004 -->

<resource version="2.3.0.1">
    <object class="wxFrame" name="frame_1">
        <style>wxDEFAULT_FRAME_STYLE</style>
        <title>frame_1</title>
        <object class="wxPanel">
        <object class="wxBoxSizer">
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
                <option>1</option>
                <flag>wxEXPAND</flag>
                <object class="wxBoxSizer">
                    <orient>wxVERTICAL</orient>
                    <object class="sizeritem">
                        <object class="wxStaticText" name="label_1">
                            <label>label_1</label>
                        </object>
                    </object>
                    <object class="sizeritem">
                        <object class="wxTextCtrl" name="text_ctrl_1">
                        </object>
                    </object>
                </object>
            </object>
        </object>
        </object>
    </object>
</resource>
"""

class MyApp(wx.wxApp):
    def OnInit(self):
        # self.res = xrc.wxXmlResource("abug.xrc")
        self.res = xrc.wxEmptyXmlResource()
        self.res.LoadFromString(someXrc)
        self.frame = self.res.LoadFrame(None, "frame_1")

        self.frame.Show(True)

        return True

    def DoExit(self, event):
        self.frame.Close(True)
        from twisted.internet import reactor
        reactor.stop()

def main(useTwisted=True):
    wxreactor.install()

    from twisted.python import log
    import sys
    log.startLogging(sys.stderr)

    myApp = MyApp(0) # XXX what is 0?

    if useTwisted:
        from twisted.internet import reactor
        reactor.registerWxApp(myApp)
        log.msg("Using Twisted reactor.")
        reactor.run(0)
    else:
        sys.stdout.write("calling myApp.MainLoop, not reactor.run.\n");
        myApp.MainLoop()

def printVersions(w):
    import twisted.copyright as tc
    import wxPython
    w("Python: %r\n" % (sys.version,))
    w("Twisted: %r\n" % (tc.version,))
    w("wxPython: %r\n" % (wxPython.__version__,))

    l = [("Twisted", tc),
         ("wxpython", wx),
         ]
    files = [module.__file__ for name, module in l]
    files = map(lambda s: s.endswith("pyc") and s[:-1] or s, files)
    files.append(sys.executable)
    cmd = "echo %s | xargs -n 1 dlocate | cut -d : -f 1 | xargs dpkg -l" % (" ".join(files),)
    # w(cmd + '\n')
    from os import system; system(cmd)
    # getProcessOutput(cmd)

if __name__ == "__main__":
    printVersions(sys.stdout.write)
    main("twisted" in sys.argv)
